#!/bin/bash

docker cp /root/conjur/conjur.yml conjur_client_1:/root/
docker-compose exec -T client conjur policy replace -b root -f /root/conjur.yml

docker cp /root/conjur/ansible.yml conjur_client_1:/root/
docker-compose exec -T client conjur policy load -b ansible -f /root/conjur/ansible.yml > /root/ansible.out

docker cp /root/conjur/server.yml conjur_client_1:/root/
docker-compose exec -T client conjur policy load -b server -f /root/server.yml

echo "/root/conjur.yml" >> ~/.bash_history
echo "/root/ansible.yml" >> ~/.bash_history
echo "/root/server.yml" >> ~/.bash_history