#!/bin/bash

export COMPOSE_INTERACTIVE_NO_CLI=1

docker cp conjur/conjur.yml root_client_1:/tmp/
docker-compose exec -T client conjur policy replace -b root -f /tmp/conjur.yml

docker cp conjur/ansible.yml root_client_1:/tmp/
docker-compose exec -T client conjur policy load -b ansible -f /tmp/ansible.yml  > conjur/ansible.out

docker cp conjur/server.yml root_client_1:/tmp/
docker-compose exec -T client conjur policy load -b server -f /tmp/server.yml