#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -euxo pipefail

if ! grep "kubectl apply -f secretless/testapp-secure.yml" ~/.bash_history; then
    fail-message "Deploy application before continuing"
fi

if [ ! -f secretless/testapp-secure.yml ]; then
    fail-message "Make sure the testapp-secure.yml file is created before continuing"
fi

exit 0