#!/bin/bash

export COMPOSE_INTERACTIVE_NO_CLI=1

docker-compose exec -T client conjur variable set -i server/host01/host -v "host01"
docker-compose exec -T client conjur variable set -i server/host01/user -v "service01"
docker-compose exec -T client conjur variable set -i server/host01/pass -v "W/4m=cS6QSZSc*nd"
docker-compose exec -T client conjur variable set -i server/host02/host -v "host02"
docker-compose exec -T client conjur variable set -i server/host02/user -v "service02"
docker-compose exec -T client conjur variable set -i server/host02/pass -v "5;LF+J4Rfqds:DZ8"
