#!/bin/bash
set -euxo pipefail

# check
echo "Checking the solution of the challenge"

api_key="$(grep API /root/conjur/admin.out | cut -d: -f2 | tr -d ' \r\n')"
admin=$(docker-compose exec -T client conjur whoami | grep "admin" | wc -l)

if ! grep "docker-compose exec -T client sh" ~/.bash_history; then
  fail-message "Initialize Conjur first before continuing"
fi

if ! grep "docker-compose -T exec client conjur" ~/.bash_history; then
  fail-message "Login to Conjur before continuing"
fi

exit 0