#!/bin/bash

docker-compose exec -T client sh -c "echo y | conjur init -u http://host01:8080 -a demo -i"

sleep 5

api_key="$(grep API /root/conjur/admin.out | cut -d: -f2 | tr -d ' \r\n')"

docker-compose exec -T client conjur login -i admin -p "$api_key"

echo "docker-compose exec -T client conjur" >> ~/.bash_history