#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -euxo pipefail

if ! grep "URL/pet" ~/.bash_history; then
    fail-message "Run the app to test it before moving forward"
fi

exit 0