#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

set -euxo pipefail

echo "This is the check script"

if ! grep "docker restart jenkins" ~/.bash_history; then
    fail-message "Restart docker before moving on"
fi

exit 0
