#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"
set -euxo pipefail

if ! grep "db.yml" ~/.bash_history; then
    fail-message "Make sure the database is setup before proceeding"
fi

if ! grep "insecure/app.yml" ~/.bash_history; then
    fail-message "Make sure the app is setup before proceeding"
fi

exit 0
