#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"

kubectl apply -f db/db.yml

kubectl apply -f insecure/app.yml

echo "db.yml" >> ~/.bash_history
echo "insecure/app.yml" >> ~/.bash_history

exit 0
