#!/bin/bash
set -euxo pipefail

# check
echo "Checking the solution of the challenge"
#if [ ! -f /root/secure-playbook/inventory ]; then
#  fail-message "Your challenge failed because you did not create an inventory file for Ansible"
#fi

#if [ ! -f /root/secure-playbook/playbook.yml ]; then
#  fail-message "Your challenge failed because you did not create an playbook.yml Ansible playbook file"
#fi

#if ! grep "cat secure-playbook/inventory" ~/.bash_history; then
#    fail-message "Review the inventory file before continuing"
#fi