#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"

grep admin admin.out
conjur login -i admin -p $(grep admin admin.out | cut -c20-)
conjur user change-password -p MySecretP@ss1
conjur logout && \
conjur login -i admin -p MySecretP@ss1

echo "conjur login" >> ~/.bash_history

exit 0
