#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"

grep admin admin.out
conjur authn login -u admin -p $(grep admin admin.out | cut -c20-)
conjur user update_password -p MySecretP@ss1
conjur authn logout && \
conjur authn login -u admin -p MySecretP@ss1

echo "conjur authn login" >> ~/.bash_history

exit 0
