#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -euxo pipefail

if ! grep "cat secretless/developer-env.sh" ~/.bash_history; then
    fail-message "Check the application environment script before finishing up"
fi

exit 0
