#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -euxo pipefail

if ! grep "conjur policy load" ~/.bash_history; then
    fail-message "Add the secrets to Conjur before continuing"
fi

if ! grep "app/testapp/secret/password" ~/.bash_history; then
    fail-message "Add the secrets to Conjur before continuing"
fi

if ! grep "app/testapp/secret/username" ~/.bash_history; then
    fail-message "Add the secrets to Conjur before continuing"
fi

if ! grep "app/testapp/secret/host" ~/.bash_history; then
    fail-message "Add the secrets to Conjur before continuing"
fi

if ! grep "app/testapp/secret/port" ~/.bash_history; then
    fail-message "Add the secrets to Conjur before continuing"
fi

exit 0
