#!/bin/bash
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"

conjur policy load -b root -f /root/secretless/testapp-policy.yml
conjur list
conjur variable set -i app/testapp/secret/password -v "5b3e5f75cb3cdc725fe40318"
conjur variable set -i app/testapp/secret/username -v "test_app"
conjur variable set -i app/testapp/secret/host -v "testapp-db.testapp.svc.cluster.local"
conjur variable set -i app/testapp/secret/port -v "5432"

echo "conjur policy load -b root" >> ~/.bash_history
echo "app/testapp/secret/password" >> ~/.bash_history
echo "app/testapp/secret/username" >> ~/.bash_history
echo "app/testapp/secret/host" >> ~/.bash_history
echo "app/testapp/secret/port" >> ~/.bash_history

exit 0
