#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

set -euxo pipefail

echo "This is the check script"

if ! grep "conjur-cli" ~/.bash_history; then
    fail-message "Make sure you load the Conjur policy before continuing"
fi

exit 0
