#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

set -euxo pipefail

echo "This is the check script"

if ! grep "docker exec conjur-cli" ~/.bash_history; then
    fail-message "Your challenge failed because you did not not load the Conjur policy"
fi

exit 0
