version: "3"
virtualmachines:
- name: host01
  image: instruqt-sean/docker-201021
  shell: /bin/bash
  machine_type: n1-standard-1
- name: host02
  image: instruqt-sean/docker-201021
  shell: /bin/bash
  machine_type: n1-standard-1
