#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -euxo pipefail

if ! grep "docker exec conjur-cli conjur init" ~/.bash_history; then
    fail-message "Make sure you initialize the Conjur client before continuing"
fi

if ! grep "docker exec conjur-cli conjur login" ~/.bash_history; then
    fail-message "Make sure you login to Conjur before continuing"
fi

exit 0