#!/bin/bash
set -euxo pipefail

# check
echo "Checking the solution of the challenge"
#if [ ! -f /root/conjur/grant_conjur_id.yml ]; then
#  fail-message "Your challenge failed because you did not create a grant_conjur_id.yml file"
#fi

exit 0