#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

set -euxo pipefail

if ! grep "conjur policy load" ~/.bash_history; then
    fail-message "Add the secrets to Conjur before continuing"
fi

if [ ! -f ./secretless/app-policy.yml ]; then
    fail-message "No file was found at ./secretless/app-policy.yml"
fi

if [ ! -f secretless/conjur-authenticator-role.yml ]; then
    fail-message "No file was found at secretless/conjur-authenticator-role.yml"
fi

if ! grep "secretless/conjur-authenticator-role.yml" ~/.bash_history; then
    fail-message "Store the configuration in a ConfigMap before continuing"
fi

exit 0
